### ISSUE TITLE
Error in installation on Mautic 3.2.4

### ISSUE THREAD

**Issue by douglara** [mtcextendee/mautic-extendee-webhook-response-bundle#3]
I install add repository folder in `plugins/MauticExtendeeWebhookResponseBundle`

PHP version 7.3.26

```

./console mautic:plugins:reload
PHP Fatal error:  Uncaught Error: Undefined class constant 'ON_WEBHOOK_RESPONSE' in /mautic/htdocs/plugins/MauticExtendeeWebhookResponseBundle/EventListener/SendWebhookSubscriber.php:47
Stack trace:
#0 /mautic/htdocs/vendor/symfony/event-dispatcher/DependencyInjection/RegisterListenersPass.php(135): MauticPlugin\MauticExtendeeWebhookResponseBundle\EventListener\SendWebhookSubscriber::getSubscribedEvents()
#1 /mautic/htdocs/vendor/symfony/event-dispatcher/EventDispatcher.php(169): Symfony\Component\EventDispatcher\DependencyInjection\ExtractingEventDispatcher::getSubscribedEvents()
#2 /mautic/htdocs/vendor/symfony/event-dispatcher/DependencyInjection/RegisterListenersPass.php(103): Symfony\Component\EventDispatcher\EventDispatcher->addSubscriber(Object(Symfony\Component\EventDispatcher\DependencyInjection\ExtractingEventDispatcher))
#3 /mautic/htdocs/vendor/symfony/dependency-injection/Compiler/Compiler.php(140): Symfony\Component\EventDispatch in /mautic/htdocs/plugins/MauticExtendeeWebhookResponseBundle/EventListener/SendWebhookSubscriber.php on line 47
root@ip-172-31-54-100:/mautic/htdocs/bin# ./console mautic:plugins:reload
PHP Fatal error:  Uncaught Error: Undefined class constant 'ON_WEBHOOK_RESPONSE' in /mautic/htdocs/plugins/MauticExtendeeWebhookResponseBundle/EventListener/SendWebhookSubscriber.php:47
Stack trace:
#0 /mautic/htdocs/vendor/symfony/event-dispatcher/DependencyInjection/RegisterListenersPass.php(135): MauticPlugin\MauticExtendeeWebhookResponseBundle\EventListener\SendWebhookSubscriber::getSubscribedEvents()
#1 /mautic/htdocs/vendor/symfony/event-dispatcher/EventDispatcher.php(169): Symfony\Component\EventDispatcher\DependencyInjection\ExtractingEventDispatcher::getSubscribedEvents()
#2 /mautic/htdocs/vendor/symfony/event-dispatcher/DependencyInjection/RegisterListenersPass.php(103): Symfony\Component\EventDispatcher\EventDispatcher->addSubscriber(Object(Symfony\Component\EventDispatcher\DependencyInjection\ExtractingEventDispatcher))
#3 /mautic/htdocs/vendor/symfony/dependency-injection/Compiler/Compiler.php(140): Symfony\Component\EventDispatch in /mautic/htdocs/plugins/MauticExtendeeWebhookResponseBundle/EventListener/SendWebhookSubscriber.php on line 47
```

**Comment by kuzmany** [comment]
Mautic  need this PR https://github.com/mautic/mautic/pull/6873
